import kotlinx.kover.gradle.plugin.dsl.AggregationType
import kotlinx.kover.gradle.plugin.dsl.CoverageUnit

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.detekt)
    alias(libs.plugins.hilt.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.kover)
    alias(libs.plugins.ksp)
    alias(libs.plugins.room)
}

android {
    namespace = "pt.tiagoduarte.challenge"
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId = "pt.tiagoduarte.challenge"
        minSdk = 24
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable = false
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    @Suppress("UnstableApiUsage")
    testFixtures {
        enable = true
    }

    flavorDimensions += "appMode"
    productFlavors {
        create("listing") {
            dimension = "appMode"
            applicationIdSuffix = ".listing"
            versionNameSuffix = "-listing"
        }
        create("form") {
            dimension = "appMode"
            applicationIdSuffix = ".form"
            versionNameSuffix = "-form"
        }
    }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.compose.material3)

    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.hilt.navigation.compose)
    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    implementation(libs.hilt.android)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.okhttp)
    implementation(libs.okhttp.logging.interceptor)
    implementation(libs.retrofit.core)
    implementation(libs.retrofit.converter.kotlinx.serialization)

    ksp(libs.androidx.room.compiler)
    ksp(libs.hilt.android.compiler)

    debugImplementation(libs.androidx.compose.ui.test.manifest)
    debugImplementation(libs.androidx.compose.ui.tooling)

    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)

    testFixturesImplementation(platform(libs.androidx.compose.bom))
    testFixturesImplementation(libs.androidx.compose.runtime)

    detektPlugins(libs.compose.rules.detekt)
}

detekt {
    buildUponDefaultConfig = true
    allRules = false
    autoCorrect = false
    config.setFrom(files("$rootDir/config/detekt/detekt.yml"))
}

room {
    schemaDirectory("$projectDir/schemas")
}

kover {
    reports {
        filters {
            excludes {
                annotatedBy("androidx.compose.ui.tooling.preview.Preview")
                annotatedBy("androidx.compose.runtime.Composable")

                classes(
                    // Generated by Hilt/Dagger/Room/AGP — no hand-written logic, not exercised by
                    // unit tests. Patterns need a leading '*' since kover matches the FULL
                    // qualified name, not just the simple class name.
                    "*_Factory",
                    "*_Factory\$*",
                    "*_MembersInjector",
                    "*_Impl",
                    "*_Impl\$*",
                    "*Hilt_*",
                    "*_HiltComponents*",
                    "*_HiltModules*",
                    "*Dagger*",
                    "*ComposableSingletons*",
                    "dagger.hilt.internal.aggregatedroot.codegen.*",
                    "hilt_aggregated_deps.*",
                    "pt.tiagoduarte.challenge.BuildConfig",

                    // Application classes — Hilt bootstrap only, no logic
                    "pt.tiagoduarte.challenge.listing.ListingApp",
                    "pt.tiagoduarte.challenge.form.FormApp",

                    // Activities and DI wiring — Android framework glue, exercised by instrumented
                    // tests rather than unit tests
                    "pt.tiagoduarte.challenge.listing.ListingActivity",
                    "pt.tiagoduarte.challenge.form.FormActivity",
                    "pt.tiagoduarte.challenge.listing.di.*",
                    "pt.tiagoduarte.challenge.data.local.db.AppDatabase",

                    // Composable theme — UI, exercised by instrumented tests, not unit tests
                    "pt.tiagoduarte.challenge.ui.theme.*",

                    // Thin network client wiring, no branching logic of its own
                    "pt.tiagoduarte.challenge.data.remote.RetrofitClient",

                    // Retrofit interface (declarative, no method bodies) and plain DTOs
                    // (compiler-generated equals/hashCode only, no hand-written logic)
                    "pt.tiagoduarte.challenge.data.remote.api.*",
                    "pt.tiagoduarte.challenge.data.remote.model.*",

                    // Context extension property backing the DataStore instance — needs a real
                    // Android Context, exercised by instrumented tests rather than unit tests
                    "pt.tiagoduarte.challenge.data.local.prefs.AppPreferencesImplKt",
                )
            }
        }

        verify {
            rule("line-coverage") {
                minBound(
                    // 80% leaves headroom for UI/DI code landing before its own tests do, while
                    // still catching real regressions in the business-logic layer.
                    minValue = 80,
                    coverageUnits = CoverageUnit.LINE,
                    aggregationForGroup = AggregationType.COVERED_PERCENTAGE
                )
            }
            rule("branch-coverage") {
                minBound(
                    minValue = 80,
                    coverageUnits = CoverageUnit.BRANCH,
                    aggregationForGroup = AggregationType.COVERED_PERCENTAGE
                )
            }
        }
    }
}
