name: 🧪 CI

on:
  pull_request:
    branches: [ develop, main ]

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.head.label || github.ref }}'
  cancel-in-progress: true

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GRADLE_OPTS: "-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx3g"
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: ./.github/actions/setup-java
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :app:assembleDebug --stacktrace

  android-test:
    name: Android Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GRADLE_OPTS: "-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx3g"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :app:testDebugUnitTest --stacktrace
      - run: ./gradlew :app:koverHtmlReport :app:koverVerify --stacktrace
      - name: Upload Kover HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kover-html-report
          path: app/build/reports/kover/html/

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GRADLE_OPTS: "-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx3g"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :app:lintDebug --stacktrace
      - name: Upload Lint HTML report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: lint-html-report
          path: app/build/reports/lint-results-debug.html

  finish:
    name: 🏁 Finish
    if: ${{ !cancelled() }}
    needs:
      - android-build
      - android-test
      - static-analysis
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        name: Fail
        run: exit 1
